classDiagram
direction TB

class TradeProcessor {
  - LotSize: float
  + ProcessTrades(stream: Stream): void
  - Parse(lines: List): IEnumerable
  - MapTradeDataToTradeRecord(fields: IReadOnlyList): TradeRecord
  - ValidateTradeData(fields: IReadOnlyList, currentLine: int): bool
  - StoreTrades(trades: IEnumerable): void
  - ReadTradData(stream: Stream): List
}
