@startuml
skinparam backgroundColor  #1E1E1E
skinparam DefaultFontColor #A9DCDF
skinparam DefaultFontSize 16
skinparam DefaultFontName JetBrains Mono

skinparam class {
  BackgroundColor #1E1E1E
  BorderColor #2D91AF
  ArrowColor #FF8000
  BorderThickness 2
}

skinparam package {
  BackgroundColor #0
  BorderColor #2D91AF
}

skinparam note {
  BackgroundColor #565656
  BorderColor #F78782
  FontColor #A9DCDF
}
hide empty members

class Program {
    - static void Main()
}

class TradeRecord {
    + int Id { get; init; }
    + string DestinationCurrency { get; init; }
    + float Lots { get; init; }
    + decimal Price { get; init; }
    + string SourceCurrency { get; init; }
}

class TradeProcessor {
    - const float LotSize
    + static void ProcessTrades(Stream stream)
    - static IEnumerable<TradeRecord> Parse(List<string> lines)
    - static TradeRecord MapTradeDataToTradeRecord(IReadOnlyList<string> fields)
    - static bool ValidateTradeData(IReadOnlyList<string> fields, int currentLine)
    - static void StoreTrades(IEnumerable<TradeRecord> trades)
    - static List<string> ReadTradData(Stream stream)
}

Program --> TradeProcessor : uses
TradeProcessor --> TradeRecord : uses

@enduml
