@startuml

interface ITradeDataProvider{
+ List<string> GetTradeData(Stream stream)
}
interface ITradeParser
{
 + List<TradeRecord> Parse(List<string> lines)
}
interface ITradeStorage
{
  + void Persist(List<TradeRecord> trades)
}

class TradeStorage {
+ void Persist(List<TradeRecord> trades)
}

class TradeDataProvider {
+ List<string> GetTradeData(Stream stream)
}
class TradeParser {
- const float LotSize = 100
+ List<TradeRecord> Parse(List<string> lines)
- static TradeRecord MapTradeDataToTradeRecord(IReadOnlyList<string> fields)
- static bool ValidateTradeData(IReadOnlyList<string> fields, int currentLine)
}

note right of TradeParser::MapTradeDataToTradeRecord
static method since it does not use any instance data
end note
note right of TradeParser::ValidateTradeData
static method since it does not use any instance data
end note


class TradeProcessor {
 - readonly ITradeParser _tradeParser;
 - readonly ITradeStorage _tradeStorage;
 - readonly ITradeDataProvider _tradeDataProvider
 + TradeProcessor(ITradeParser tradeParser, ITradeStorage tradeStorage, ITradeDataProvider tradeDataProvider)
 + void ProcessTrades(Stream stream)
}

note top of TradeProcessor
    Can no longer be static since it uses instance data 
end note
note right of TradeProcessor::TradeProcessor
    Constructor injection 
end note

TradeProcessor o---ITradeParser
TradeProcessor o---ITradeDataProvider
TradeProcessor o---ITradeStorage

TradeParser ...up|> ITradeParser
TradeStorage ...up|> ITradeStorage
TradeDataProvider ...up|> ITradeDataProvider

note right of TradeDataProvider::GetTradeData
    Can no longer be static
end note




@enduml
